/** @generated from data/exports/portal-crm/routes.json — run: npm run codegen:routes */
import type { StaticRoute } from '../../lib/handler-ctx.js'
import { compileController } from '../../lib/compile-controller.js'

export const PortalCrmRoutes: StaticRoute[] = [
  // 0 activity DELETE /Activity/:id (6cb597f7)
  {
    module: "activity",
    method: "DELETE",
    path: "/Activity/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3ueqtq000xmk5scykbq2ez",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Activity;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Activity missing\" });\n  try {\n    await model.delete(String(ctx.params.id));\n    return ctx.reply.send({ ok: true });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 1 activity GET /Activity (d67b089c)
  {
    module: "activity",
    method: "GET",
    path: "/Activity",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3ueqtk000nmk5sevqol7bm",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Activity;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Activity missing\" });\n  const rows = await model.findMany(ctx.query || {});\n  return ctx.reply.send({ data: rows, count: rows.length });\n}\nmodule.exports = { handler };"),
  },
  // 2 activity GET /Activity/:id (ec53e101)
  {
    module: "activity",
    method: "GET",
    path: "/Activity/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3ueqtn000rmk5smf50baoo",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Activity;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Activity missing\" });\n  const row = await model.findById(String(ctx.params.id));\n  if (!row) return ctx.reply.status(404).send({ error: \"not found\" });\n  return ctx.reply.send({ data: row });\n}\nmodule.exports = { handler };"),
  },
  // 3 activity PATCH /Activity/:id (5c04b2a6)
  {
    module: "activity",
    method: "PATCH",
    path: "/Activity/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3ueqto000tmk5s81ke6uq2",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Activity;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Activity missing\" });\n  try {\n    const row = await model.update(String(ctx.params.id), Object.assign({}, ctx.body || {}));\n    return ctx.reply.send({ data: row });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 4 activity POST /Activity (f646d684)
  {
    module: "activity",
    method: "POST",
    path: "/Activity",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3ueqtm000pmk5sh6pa55ib",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Activity;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Activity missing\" });\n  const row = await model.create(Object.assign({}, ctx.body || {}));\n  return ctx.reply.status(201).send({ data: row });\n}\nmodule.exports = { handler };"),
  },
  // 5 activity PUT /Activity/:id (1d2e201c)
  {
    module: "activity",
    method: "PUT",
    path: "/Activity/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3ueqtp000vmk5skfvhu4oe",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Activity;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Activity missing\" });\n  try {\n    const row = await model.update(String(ctx.params.id), Object.assign({}, ctx.body || {}));\n    return ctx.reply.send({ data: row });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 6 appconfig DELETE /AppConfig/:id (c19561d0)
  {
    module: "appconfig",
    method: "DELETE",
    path: "/AppConfig/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3ueqtv001bmk5satozckn6",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.AppConfig;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model AppConfig missing\" });\n  try {\n    await model.delete(String(ctx.params.id));\n    return ctx.reply.send({ ok: true });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 7 appconfig GET /AppConfig (b6603ef1)
  {
    module: "appconfig",
    method: "GET",
    path: "/AppConfig",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3ueqtr0011mk5sui4rkwbg",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.AppConfig;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model AppConfig missing\" });\n  const rows = await model.findMany(ctx.query || {});\n  return ctx.reply.send({ data: rows, count: rows.length });\n}\nmodule.exports = { handler };"),
  },
  // 8 appconfig GET /AppConfig/:id (a3b9040b)
  {
    module: "appconfig",
    method: "GET",
    path: "/AppConfig/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3ueqtt0015mk5s7r7bg5n7",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.AppConfig;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model AppConfig missing\" });\n  const row = await model.findById(String(ctx.params.id));\n  if (!row) return ctx.reply.status(404).send({ error: \"not found\" });\n  return ctx.reply.send({ data: row });\n}\nmodule.exports = { handler };"),
  },
  // 9 appconfig PATCH /AppConfig/:id (c20e3690)
  {
    module: "appconfig",
    method: "PATCH",
    path: "/AppConfig/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3ueqtu0017mk5srcavk6ur",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.AppConfig;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model AppConfig missing\" });\n  try {\n    const row = await model.update(String(ctx.params.id), Object.assign({}, ctx.body || {}));\n    return ctx.reply.send({ data: row });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 10 appconfig POST /AppConfig (6b25b808)
  {
    module: "appconfig",
    method: "POST",
    path: "/AppConfig",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3ueqts0013mk5sd6zcylz8",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.AppConfig;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model AppConfig missing\" });\n  const row = await model.create(Object.assign({}, ctx.body || {}));\n  return ctx.reply.status(201).send({ data: row });\n}\nmodule.exports = { handler };"),
  },
  // 11 appconfig PUT /AppConfig/:id (1b4c01bf)
  {
    module: "appconfig",
    method: "PUT",
    path: "/AppConfig/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3ueqtv0019mk5say22hl53",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.AppConfig;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model AppConfig missing\" });\n  try {\n    const row = await model.update(String(ctx.params.id), Object.assign({}, ctx.body || {}));\n    return ctx.reply.send({ data: row });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 12 client DELETE /Client/:id (024ff2d2)
  {
    module: "client",
    method: "DELETE",
    path: "/Client/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequ1001pmk5sutsqyl2c",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Client;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Client missing\" });\n  try {\n    await model.delete(String(ctx.params.id));\n    return ctx.reply.send({ ok: true });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 13 client GET /Client (0f0fac6e)
  {
    module: "client",
    method: "GET",
    path: "/Client",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3ueqtx001fmk5sszgsc954",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Client;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Client missing\" });\n  const rows = await model.findMany(ctx.query || {});\n  return ctx.reply.send({ data: rows, count: rows.length });\n}\nmodule.exports = { handler };"),
  },
  // 14 client GET /Client/:id (e3ac5972)
  {
    module: "client",
    method: "GET",
    path: "/Client/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3ueqtz001jmk5s531wxnvu",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Client;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Client missing\" });\n  const row = await model.findById(String(ctx.params.id));\n  if (!row) return ctx.reply.status(404).send({ error: \"not found\" });\n  return ctx.reply.send({ data: row });\n}\nmodule.exports = { handler };"),
  },
  // 15 client PATCH /Client/:id (047def17)
  {
    module: "client",
    method: "PATCH",
    path: "/Client/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequ0001lmk5suidyvzk6",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Client;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Client missing\" });\n  try {\n    const row = await model.update(String(ctx.params.id), Object.assign({}, ctx.body || {}));\n    return ctx.reply.send({ data: row });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 16 client POST /Client (43bb8e3f)
  {
    module: "client",
    method: "POST",
    path: "/Client",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3ueqty001hmk5s8l2rznf2",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Client;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Client missing\" });\n  const row = await model.create(Object.assign({}, ctx.body || {}));\n  return ctx.reply.status(201).send({ data: row });\n}\nmodule.exports = { handler };"),
  },
  // 17 client PUT /Client/:id (cabe2de6)
  {
    module: "client",
    method: "PUT",
    path: "/Client/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequ0001nmk5scrvmfhpu",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Client;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Client missing\" });\n  try {\n    const row = await model.update(String(ctx.params.id), Object.assign({}, ctx.body || {}));\n    return ctx.reply.send({ data: row });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 18 crm-domain GET /activities (e674484e)
  {
    module: "crm-domain",
    method: "GET",
    path: "/activities",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms50gcjn000lmtp9h781mjve",
    handler: compileController("async function handler(ctx) {\n  var Activity = ctx.models.Activity;\n  var Client = ctx.models.Client;\n  if (!Activity) return ctx.reply.status(500).send({ error: \"Model Activity missing\" });\n  var q = ctx.query || {};\n  var ownerId = q.ownerId;\n  var all = await Activity.findMany({});\n  var clients = Client ? await Client.findMany({}) : [];\n  var byId = {};\n  clients.forEach(function (c) { byId[c.id] = c; });\n  var rows = all.filter(function (a) {\n    if (ownerId && String(a.ownerId) !== String(ownerId)) return false;\n    return true;\n  });\n  rows.sort(function (a, b) {\n    return String(a.scheduledAt || \"\").localeCompare(String(b.scheduledAt || \"\"));\n  });\n  var data = rows.map(function (a) {\n    var c = a.clientId ? byId[a.clientId] : null;\n    return Object.assign({}, a, { client: c ? { id: c.id, name: c.name } : null });\n  });\n  return ctx.reply.send({ data: data, count: data.length });\n}\nmodule.exports = { handler };"),
  },
  // 19 crm-domain GET /clients (9464d651)
  {
    module: "crm-domain",
    method: "GET",
    path: "/clients",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms50gcj10007mtp91xoyc369",
    handler: compileController("async function handler(ctx) {\n  var Client = ctx.models.Client;\n  if (!Client) return ctx.reply.status(500).send({ error: \"Model Client missing\" });\n  var q = ctx.query || {};\n  var search = q.q ? String(q.q).toLowerCase() : \"\";\n  var tipo = q.tipo || q.type || \"\";\n  var ownerId = q.ownerId;\n  var scopeOwner = q.scopeOwner;\n  var all = await Client.findMany({});\n  var rows = all.filter(function (c) {\n    if (ownerId === \"null\" || ownerId === \"__null__\") {\n      if (c.ownerId != null && c.ownerId !== \"\") return false;\n    } else if (ownerId) {\n      if (String(c.ownerId) !== String(ownerId)) return false;\n    } else if (scopeOwner) {\n      // exclude pool when listing \"my/team\" clients\n      if (c.ownerId == null || c.ownerId === \"\") return false;\n      if (scopeOwner !== \"admin\" && String(c.ownerId) !== String(scopeOwner)) return false;\n    } else {\n      if (c.ownerId == null || c.ownerId === \"\") return false;\n    }\n    if (tipo === \"lead\" || tipo === \"cliente\") {\n      if (c.type !== tipo) return false;\n    }\n    if (!search) return true;\n    var name = String(c.name || \"\").toLowerCase();\n    var company = String(c.company || \"\").toLowerCase();\n    return name.indexOf(search) >= 0 || company.indexOf(search) >= 0;\n  });\n  rows.sort(function (a, b) {\n    return String(b.createdAt || \"\").localeCompare(String(a.createdAt || \"\"));\n  });\n  return ctx.reply.send({ data: rows.slice(0, 200), count: rows.length });\n}\nmodule.exports = { handler };"),
  },
  // 20 crm-domain GET /deals (d79dbdac)
  {
    module: "crm-domain",
    method: "GET",
    path: "/deals",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms50gcjb000dmtp97ihtp6de",
    handler: compileController("async function handler(ctx) {\n  var Deal = ctx.models.Deal;\n  var Client = ctx.models.Client;\n  if (!Deal) return ctx.reply.status(500).send({ error: \"Model Deal missing\" });\n  var q = ctx.query || {};\n  var status = q.status || \"open\";\n  var ownerId = q.ownerId;\n  var all = await Deal.findMany({});\n  var clients = Client ? await Client.findMany({}) : [];\n  var byId = {};\n  clients.forEach(function (c) { byId[c.id] = c; });\n  var rows = all.filter(function (d) {\n    if (status && status !== \"all\" && d.status !== status) return false;\n    if (ownerId && String(d.ownerId) !== String(ownerId)) return false;\n    return true;\n  });\n  var data = rows.map(function (d) {\n    var c = byId[d.clientId];\n    return Object.assign({}, d, {\n      value: d.value != null ? Number(d.value) : null,\n      client: c ? { id: c.id, name: c.name } : { id: d.clientId, name: \"—\" },\n    });\n  });\n  return ctx.reply.send({ data: data, count: data.length });\n}\nmodule.exports = { handler };"),
  },
  // 21 crm-domain GET /goals (8d44bba0)
  {
    module: "crm-domain",
    method: "GET",
    path: "/goals",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms50gck4000xmtp9gl4w465x",
    handler: compileController("async function handler(ctx) {\n  var Goal = ctx.models.Goal;\n  if (!Goal) return ctx.reply.status(500).send({ error: \"Model Goal missing\" });\n  var q = ctx.query || {};\n  var all = await Goal.findMany({});\n  var rows = all.filter(function (g) {\n    if (q.userId && String(g.userId) !== String(q.userId)) return false;\n    if (q.periodMonth && Number(g.periodMonth) !== Number(q.periodMonth)) return false;\n    if (q.periodYear && Number(g.periodYear) !== Number(q.periodYear)) return false;\n    return true;\n  });\n  return ctx.reply.send({ data: rows, count: rows.length });\n}\nmodule.exports = { handler };"),
  },
  // 22 crm-domain GET /leads (6e9e9fda)
  {
    module: "crm-domain",
    method: "GET",
    path: "/leads",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms50gcis0003mtp9qzrmklzw",
    handler: compileController("async function handler(ctx) {\n  var Client = ctx.models.Client;\n  if (!Client) return ctx.reply.status(500).send({ error: \"Model Client missing\" });\n  var q = (ctx.query && ctx.query.q) ? String(ctx.query.q).toLowerCase() : \"\";\n  var all = await Client.findMany({});\n  var rows = all.filter(function (c) {\n    if (c.type !== \"lead\") return false;\n    if (c.ownerId != null && c.ownerId !== \"\") return false;\n    if (!q) return true;\n    var name = String(c.name || \"\").toLowerCase();\n    var company = String(c.company || \"\").toLowerCase();\n    var tags = Array.isArray(c.tags) ? c.tags.join(\" \").toLowerCase() : \"\";\n    return name.indexOf(q) >= 0 || company.indexOf(q) >= 0 || tags.indexOf(q) >= 0;\n  });\n  return ctx.reply.send({ data: rows, count: rows.length });\n}\nmodule.exports = { handler };"),
  },
  // 23 crm-domain GET /me/profile (1c1d9d7b)
  {
    module: "crm-domain",
    method: "GET",
    path: "/me/profile",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms50gckf0015mtp90ueu37o3",
    handler: compileController("async function handler(ctx) {\n  var Profile = ctx.models.Profile;\n  var user = ctx.user || {};\n  var uid = user.id || user.userId;\n  if (!uid) return ctx.reply.status(401).send({ error: \"Unauthorized\" });\n  if (!Profile) {\n    return ctx.reply.send({\n      id: uid,\n      email: user.email || null,\n      fullName: user.name || null,\n      role: \"vendedor\",\n    });\n  }\n  var row = await Profile.findById(String(uid));\n  if (!row) {\n    return ctx.reply.send({\n      id: uid,\n      email: user.email || null,\n      fullName: user.name || null,\n      role: \"vendedor\",\n    });\n  }\n  return ctx.reply.send(row);\n}\nmodule.exports = { handler };"),
  },
  // 24 crm-domain GET /profiles (54e268b2)
  {
    module: "crm-domain",
    method: "GET",
    path: "/profiles",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms50gckc0013mtp9p5a63t76",
    handler: compileController("async function handler(ctx) {\n  var Profile = ctx.models.Profile;\n  if (!Profile) return ctx.reply.status(500).send({ error: \"Model Profile missing\" });\n  var all = await Profile.findMany({});\n  return ctx.reply.send({ data: all, count: all.length });\n}\nmodule.exports = { handler };"),
  },
  // 25 crm-domain GET /stages (aeb67103)
  {
    module: "crm-domain",
    method: "GET",
    path: "/stages",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms50gcjw000rmtp9lybo0pzv",
    handler: compileController("async function handler(ctx) {\n  var Stage = ctx.models.Stage;\n  if (!Stage) return ctx.reply.status(500).send({ error: \"Model Stage missing\" });\n  var all = await Stage.findMany({});\n  var rows = all.filter(function (s) { return s.active !== false; });\n  rows.sort(function (a, b) { return Number(a.order || 0) - Number(b.order || 0); });\n  return ctx.reply.send({ data: rows, count: rows.length });\n}\nmodule.exports = { handler };"),
  },
  // 26 crm-domain GET /teams (28986ac5)
  {
    module: "crm-domain",
    method: "GET",
    path: "/teams",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms50gck90011mtp9qdz95rf6",
    handler: compileController("async function handler(ctx) {\n  var Team = ctx.models.Team;\n  if (!Team) return ctx.reply.status(500).send({ error: \"Model Team missing\" });\n  var all = await Team.findMany({});\n  return ctx.reply.send({ data: all, count: all.length });\n}\nmodule.exports = { handler };"),
  },
  // 27 crm-domain PATCH /clients/:id (3be66756)
  {
    module: "crm-domain",
    method: "PATCH",
    path: "/clients/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms50gcj7000bmtp9in0090mt",
    handler: compileController("async function handler(ctx) {\n  var Client = ctx.models.Client;\n  if (!Client) return ctx.reply.status(500).send({ error: \"Model Client missing\" });\n  var id = String((ctx.params && ctx.params.id) || \"\");\n  var body = Object.assign({}, ctx.body || {});\n  body.updatedAt = new Date().toISOString();\n  try {\n    var row = await Client.update(id, body);\n    if (!row) return ctx.reply.status(404).send({ error: \"Not found\" });\n    return ctx.reply.send(row);\n  } catch (e) {\n    return ctx.reply.status(400).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 28 crm-domain PATCH /deals/:id (057ce5a3)
  {
    module: "crm-domain",
    method: "PATCH",
    path: "/deals/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms50gcjk000jmtp909864ymm",
    handler: compileController("async function handler(ctx) {\n  var Deal = ctx.models.Deal;\n  var Client = ctx.models.Client;\n  if (!Deal) return ctx.reply.status(500).send({ error: \"Model Deal missing\" });\n  var id = String((ctx.params && ctx.params.id) || \"\");\n  var body = Object.assign({}, ctx.body || {});\n  var deal = await Deal.findById(id);\n  if (!deal) return ctx.reply.status(404).send({ error: \"Negociação não encontrada\" });\n  body.updatedAt = new Date().toISOString();\n  if (body.status === \"won\" || body.status === \"lost\") {\n    body.closedAt = body.closedAt || new Date().toISOString();\n  }\n  var updated = await Deal.update(id, body);\n  if (body.status === \"won\" && Client && deal.clientId) {\n    try {\n      await Client.update(deal.clientId, { type: \"cliente\", updatedAt: new Date().toISOString() });\n    } catch (e) {}\n  }\n  return ctx.reply.send(updated);\n}\nmodule.exports = { handler };"),
  },
  // 29 crm-domain PATCH /deals/:id/stage (788e2077)
  {
    module: "crm-domain",
    method: "PATCH",
    path: "/deals/:id/stage",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms50gcjg000hmtp9t9yew9z5",
    handler: compileController("async function handler(ctx) {\n  var Deal = ctx.models.Deal;\n  var Stage = ctx.models.Stage;\n  if (!Deal) return ctx.reply.status(500).send({ error: \"Model Deal missing\" });\n  var id = String((ctx.params && ctx.params.id) || \"\");\n  var stageId = (ctx.body && ctx.body.stageId) || null;\n  if (!stageId) return ctx.reply.status(400).send({ error: \"stageId required\" });\n  var deal = await Deal.findById(id);\n  if (!deal) return ctx.reply.status(404).send({ error: \"Negociação não encontrada\" });\n  if (Stage) {\n    var st = await Stage.findById(String(stageId));\n    if (!st) return ctx.reply.status(400).send({ error: \"Etapa inválida\" });\n  }\n  var history = Array.isArray(deal.stageHistory) ? deal.stageHistory.slice() : [];\n  history.push({ stageId: String(stageId), movedAt: new Date().toISOString() });\n  var updated = await Deal.update(id, {\n    stageId: String(stageId),\n    stageHistory: history,\n    updatedAt: new Date().toISOString(),\n  });\n  return ctx.reply.send(updated);\n}\nmodule.exports = { handler };"),
  },
  // 30 crm-domain PATCH /stages/:id (e609e429)
  {
    module: "crm-domain",
    method: "PATCH",
    path: "/stages/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms50gck1000vmtp98vuuqgw0",
    handler: compileController("async function handler(ctx) {\n  var Stage = ctx.models.Stage;\n  if (!Stage) return ctx.reply.status(500).send({ error: \"Model Stage missing\" });\n  var id = String((ctx.params && ctx.params.id) || \"\");\n  var body = Object.assign({}, ctx.body || {});\n  body.updatedAt = new Date().toISOString();\n  var row = await Stage.update(id, body);\n  if (!row) return ctx.reply.status(404).send({ error: \"Not found\" });\n  return ctx.reply.send(row);\n}\nmodule.exports = { handler };"),
  },
  // 31 crm-domain POST /activities (33565ac7)
  {
    module: "crm-domain",
    method: "POST",
    path: "/activities",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms50gcjq000nmtp9w4yqlx2w",
    handler: compileController("async function handler(ctx) {\n  var Activity = ctx.models.Activity;\n  if (!Activity) return ctx.reply.status(500).send({ error: \"Model Activity missing\" });\n  var user = ctx.user || {};\n  var uid = user.id || user.userId;\n  var body = Object.assign({}, ctx.body || {});\n  var now = new Date().toISOString();\n  if (!body.type || !body.scheduledAt) {\n    return ctx.reply.status(400).send({ error: \"type and scheduledAt required\" });\n  }\n  if (!body.ownerId) body.ownerId = uid;\n  body.reminderSent = !!body.reminderSent;\n  body.createdAt = now;\n  body.updatedAt = now;\n  try {\n    var row = await Activity.create(body);\n    return ctx.reply.status(201).send(row);\n  } catch (e) {\n    return ctx.reply.status(400).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 32 crm-domain POST /activities/:id/complete (35a81d1a)
  {
    module: "crm-domain",
    method: "POST",
    path: "/activities/:id/complete",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms50gcjt000pmtp96arak7v1",
    handler: compileController("async function handler(ctx) {\n  var Activity = ctx.models.Activity;\n  if (!Activity) return ctx.reply.status(500).send({ error: \"Model Activity missing\" });\n  var id = String((ctx.params && ctx.params.id) || \"\");\n  var body = ctx.body || {};\n  var row = await Activity.findById(id);\n  if (!row) return ctx.reply.status(404).send({ error: \"Atividade não encontrada\" });\n  var patch = {\n    doneAt: new Date().toISOString(),\n    updatedAt: new Date().toISOString(),\n  };\n  if (body.notes != null) patch.notes = body.notes;\n  var updated = await Activity.update(id, patch);\n  return ctx.reply.send(updated);\n}\nmodule.exports = { handler };"),
  },
  // 33 crm-domain POST /clients (e7fa8835)
  {
    module: "crm-domain",
    method: "POST",
    path: "/clients",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms50gcj50009mtp9msqo8kp8",
    handler: compileController("async function handler(ctx) {\n  var Client = ctx.models.Client;\n  if (!Client) return ctx.reply.status(500).send({ error: \"Model Client missing\" });\n  var user = ctx.user || {};\n  var uid = user.id || user.userId;\n  var body = Object.assign({}, ctx.body || {});\n  var now = new Date().toISOString();\n  if (!body.name) return ctx.reply.status(400).send({ error: \"name required\" });\n  if (!body.type) body.type = \"lead\";\n  if (body.ownerId === undefined) body.ownerId = uid || null;\n  if (!Array.isArray(body.tags)) body.tags = body.tags ? [String(body.tags)] : [];\n  body.createdAt = body.createdAt || now;\n  body.updatedAt = now;\n  try {\n    var row = await Client.create(body);\n    return ctx.reply.status(201).send(row);\n  } catch (e) {\n    return ctx.reply.status(400).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 34 crm-domain POST /deals (01043f41)
  {
    module: "crm-domain",
    method: "POST",
    path: "/deals",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms50gcjd000fmtp95p4np3fx",
    handler: compileController("async function handler(ctx) {\n  var Deal = ctx.models.Deal;\n  var Stage = ctx.models.Stage;\n  if (!Deal) return ctx.reply.status(500).send({ error: \"Model Deal missing\" });\n  var user = ctx.user || {};\n  var uid = user.id || user.userId;\n  var body = Object.assign({}, ctx.body || {});\n  var now = new Date().toISOString();\n  if (!body.title || !body.clientId) {\n    return ctx.reply.status(400).send({ error: \"title and clientId required\" });\n  }\n  if (!body.ownerId) body.ownerId = uid;\n  if (!body.stageId && Stage) {\n    var stages = await Stage.findMany({});\n    stages.sort(function (a, b) { return Number(a.order || 0) - Number(b.order || 0); });\n    if (stages[0]) body.stageId = stages[0].id;\n  }\n  if (!body.stageId) return ctx.reply.status(400).send({ error: \"stageId required\" });\n  body.status = body.status || \"open\";\n  body.stageHistory = Array.isArray(body.stageHistory) ? body.stageHistory : [];\n  body.createdAt = now;\n  body.updatedAt = now;\n  try {\n    var row = await Deal.create(body);\n    return ctx.reply.status(201).send(row);\n  } catch (e) {\n    return ctx.reply.status(400).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 35 crm-domain POST /goals (4c35e25c)
  {
    module: "crm-domain",
    method: "POST",
    path: "/goals",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms50gck6000zmtp99bor2mm9",
    handler: compileController("async function handler(ctx) {\n  var Goal = ctx.models.Goal;\n  if (!Goal) return ctx.reply.status(500).send({ error: \"Model Goal missing\" });\n  var body = Object.assign({}, ctx.body || {});\n  var now = new Date().toISOString();\n  if (!body.userId || body.periodMonth == null || body.periodYear == null) {\n    return ctx.reply.status(400).send({ error: \"userId, periodMonth, periodYear required\" });\n  }\n  body.targetValue = Number(body.targetValue || 0);\n  body.targetDeals = Number(body.targetDeals || 0);\n  body.createdAt = now;\n  body.updatedAt = now;\n  var row = await Goal.create(body);\n  return ctx.reply.status(201).send(row);\n}\nmodule.exports = { handler };"),
  },
  // 36 crm-domain POST /leads/:id/claim (f9cdc93e)
  {
    module: "crm-domain",
    method: "POST",
    path: "/leads/:id/claim",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms50gciy0005mtp953u1tire",
    handler: compileController("async function handler(ctx) {\n  var Client = ctx.models.Client;\n  if (!Client) return ctx.reply.status(500).send({ error: \"Model Client missing\" });\n  var user = ctx.user || {};\n  var uid = user.id || user.userId;\n  if (!uid) return ctx.reply.status(401).send({ error: \"Unauthorized\" });\n  var id = String((ctx.params && ctx.params.id) || \"\");\n  var row = await Client.findById(id);\n  if (!row) return ctx.reply.status(404).send({ error: \"Lead não encontrado\" });\n  if (row.type !== \"lead\") return ctx.reply.status(400).send({ error: \"Não é um lead\" });\n  if (row.ownerId != null && row.ownerId !== \"\") {\n    return ctx.reply.status(409).send({ error: \"Este lead já foi pego por outro vendedor.\" });\n  }\n  var updated = await Client.update(id, {\n    ownerId: uid,\n    updatedAt: new Date().toISOString(),\n  });\n  return ctx.reply.send({ success: true, client: updated });\n}\nmodule.exports = { handler };"),
  },
  // 37 crm-domain POST /stages (8122a93e)
  {
    module: "crm-domain",
    method: "POST",
    path: "/stages",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms50gcjz000tmtp9bwtqelwd",
    handler: compileController("async function handler(ctx) {\n  var Stage = ctx.models.Stage;\n  if (!Stage) return ctx.reply.status(500).send({ error: \"Model Stage missing\" });\n  var body = Object.assign({}, ctx.body || {});\n  var now = new Date().toISOString();\n  if (!body.name) return ctx.reply.status(400).send({ error: \"name required\" });\n  body.order = Number(body.order || 0);\n  body.color = body.color || \"#6366f1\";\n  body.active = body.active !== false;\n  body.createdAt = now;\n  body.updatedAt = now;\n  var row = await Stage.create(body);\n  return ctx.reply.status(201).send(row);\n}\nmodule.exports = { handler };"),
  },
  // 38 crm-domain-leads DELETE /clients/:id/filiais (19b2bec6)
  {
    module: "crm-domain-leads",
    method: "DELETE",
    path: "/clients/:id/filiais",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms5959kz001rmt01f2x9s9se",
    handler: compileController("async function handler(ctx){\n  const b=ctx.body||{};if(!b.childId)return ctx.reply.status(400).send({error:'childId obrigatorio'});\n  const upd=await ctx.models.Client.update(b.childId,{parentId:null});\n  return ctx.reply.send(upd);\n}\nmodule.exports={handler};\n"),
  },
  // 39 crm-domain-leads GET /clients/:id/filiais (d5236237)
  {
    module: "crm-domain-leads",
    method: "GET",
    path: "/clients/:id/filiais",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms5958tg001nmt01e9gmtt5t",
    handler: compileController("async function handler(ctx){\n  const id=ctx.params.id;\n  const filiais=await ctx.models.Client.findMany({parentId:id});\n  const ids=[id].concat(filiais.map(f=>f.id));\n  const deals=await ctx.models.Deal.findMany({});\n  const valorRede=deals.filter(d=>ids.indexOf(d.clientId)>=0).reduce((s,d)=>s+(Number(d.value)||0),0);\n  return ctx.reply.send({filiais,valorRede});\n}\nmodule.exports={handler};\n"),
  },
  // 40 crm-domain-leads GET /equipe (1dfb37aa)
  {
    module: "crm-domain-leads",
    method: "GET",
    path: "/equipe",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cmtanx3ry00tmqd014uxxwltj",
    handler: compileController("async function handler(ctx){\n  const uid=ctx.user&&ctx.user.id; if(!uid) return ctx.reply.status(401).send({error:'Auth necessaria'});\n  const me=await ctx.models.Profile.findById(uid);\n  if(!me||me.role!=='admin') return ctx.reply.status(403).send({error:'Apenas admin do CRM'});\n  const rows=await ctx.models.Profile.findMany({});\n  return ctx.reply.send({data:rows.map(p=>({id:p.id,email:p.email,fullName:p.fullName,role:p.role,phone:p.phone,active:p.active!==false,position:p.position}))});\n}\nmodule.exports={handler};\n"),
  },
  // 41 crm-domain-leads GET /leads/pool (6e549f31)
  {
    module: "crm-domain-leads",
    method: "GET",
    path: "/leads/pool",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms59573f001dmt01eay8cdmu",
    handler: compileController("async function handler(ctx){\n  const mat=await ctx.models.Client.findMany({isMatriz:true});\n  const out=mat.filter(r=>!r.ownerId).map(r=>({...r,status:r.status||'novo',_filiais:Math.max(0,(r.qtdLojas||1)-1)}));\n  return ctx.reply.send({data:out,count:out.length});\n}\nmodule.exports={handler};\n"),
  },
  // 42 crm-domain-leads GET /produtos (8f6e6500)
  {
    module: "crm-domain-leads",
    method: "GET",
    path: "/produtos",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms595an6001xmt01384r3lua",
    handler: compileController("async function handler(ctx){\n  const p=await ctx.models.Produto.findMany({});\n  const act=p.filter(x=>x.ativo!==false);\n  act.sort((a,b)=>((a.nome||'')+'').localeCompare((b.nome||'')+''));\n  return ctx.reply.send({data:act,count:act.length});\n}\nmodule.exports={handler};\n"),
  },
  // 43 crm-domain-leads GET /ramos (20765ca8)
  {
    module: "crm-domain-leads",
    method: "GET",
    path: "/ramos",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms5959y1001tmt01hh3zd0dl",
    handler: compileController("async function handler(ctx){\n  const r=await ctx.models.Ramo.findMany({});\n  r.sort((a,b)=>((a.nome||'')+'').localeCompare((b.nome||'')+''));\n  return ctx.reply.send({data:r,count:r.length});\n}\nmodule.exports={handler};\n"),
  },
  // 44 crm-domain-leads GET /termo/current (c9f02ea9)
  {
    module: "crm-domain-leads",
    method: "GET",
    path: "/termo/current",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms5957s0001hmt0140cefgro",
    handler: compileController("async function handler(ctx){\n  const terms=await ctx.models.Term.findMany({});\n  const cur=terms.filter(t=>t.vigente).sort((a,b)=>((b.publishedAt||'')+'').localeCompare((a.publishedAt||'')+''))[0]||null;\n  let accepted=false;\n  if(cur&&ctx.user){const acc=await ctx.models.TermAcceptance.findMany({userId:ctx.user.id});accepted=acc.some(a=>a.versao===cur.versao);}\n  return ctx.reply.send({term:cur,accepted});\n}\nmodule.exports={handler};\n"),
  },
  // 45 crm-domain-leads GET /treinamento/progresso (0e222ddf)
  {
    module: "crm-domain-leads",
    method: "GET",
    path: "/treinamento/progresso",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cmtam8adx00t0qd01eni8qh1k",
    handler: compileController("async function handler(ctx){\n  const uid=ctx.user&&ctx.user.id; if(!uid) return ctx.reply.status(401).send({error:'Auth necessaria'});\n  const rows=await ctx.models.ProgressoTreinamento.findMany({userId:uid});\n  return ctx.reply.send({data:rows.map(r=>r.moduloId)});\n}\nmodule.exports={handler};\n"),
  },
  // 46 crm-domain-leads PATCH /equipe/membro/:id (cf48afde)
  {
    module: "crm-domain-leads",
    method: "PATCH",
    path: "/equipe/membro/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cmtanx4hr00tqqd01w40w1xpz",
    handler: compileController("async function handler(ctx){\n  const uid=ctx.user&&ctx.user.id; if(!uid) return ctx.reply.status(401).send({error:'Auth necessaria'});\n  const me=await ctx.models.Profile.findById(uid);\n  if(!me||me.role!=='admin') return ctx.reply.status(403).send({error:'Apenas admin do CRM'});\n  const id=ctx.params.id; const b=ctx.body||{}; const patch={};\n  if(b.role!==undefined){ const roles=['vendedor','gerente','admin']; if(roles.indexOf(b.role)<0) return ctx.reply.status(400).send({error:'role invalido'}); patch.role=b.role; }\n  if(b.phone!==undefined) patch.phone=b.phone||null;\n  if(b.fullName!==undefined) patch.fullName=b.fullName;\n  if(b.active!==undefined) patch.active=b.active;\n  const prof=await ctx.models.Profile.update(id,patch);\n  return ctx.reply.send(prof);\n}\nmodule.exports={handler};\n"),
  },
  // 47 crm-domain-leads POST /clients/:id/filiais (0a09c384)
  {
    module: "crm-domain-leads",
    method: "POST",
    path: "/clients/:id/filiais",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms59596u001pmt010afmg2ro",
    handler: compileController("async function handler(ctx){\n  const matrizId=ctx.params.id;const b=ctx.body||{};\n  const matriz=await ctx.models.Client.findById(matrizId);\n  if(!matriz)return ctx.reply.status(404).send({error:'Matriz nao encontrada'});\n  if(b.childId){\n    if(b.childId===matrizId)return ctx.reply.status(400).send({error:'Nao pode ser filial de si mesma'});\n    const upd=await ctx.models.Client.update(b.childId,{parentId:matrizId,ownerId:matriz.ownerId||null,temperaturaVendedor:null,temperaturaCalculada:null});\n    return ctx.reply.status(201).send(upd);\n  }\n  if(b.name&&b.name.trim()){\n    const nm=b.name.trim();\n    const f=await ctx.models.Client.create({id:'c'+Date.now().toString(36)+Math.random().toString(36).slice(2,10),name:nm,empresa:nm,parentId:matrizId,ownerId:matriz.ownerId||null,ramoId:matriz.ramoId||null,cidade:matriz.cidade||null,uf:matriz.uf||null,type:matriz.type||'lead',tags:['filial'],status:'novo',createdAt:new Date().toISOString()});\n    return ctx.reply.status(201).send(f);\n  }\n  return ctx.reply.status(400).send({error:'Informe name ou childId'});\n}\nmodule.exports={handler};\n"),
  },
  // 48 crm-domain-leads POST /clients/:id/status (7564a371)
  {
    module: "crm-domain-leads",
    method: "POST",
    path: "/clients/:id/status",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms595b02001zmt016cjiri5k",
    handler: compileController("async function handler(ctx){\n  const uid=ctx.user&&ctx.user.id;if(!uid)return ctx.reply.status(401).send({error:'Auth necessaria'});\n  const id=ctx.params.id;const b=ctx.body||{};\n  const st=b.status;const valid=['novo','em_contato','qualificado','sem_interesse','descartado'];\n  if(valid.indexOf(st)<0)return ctx.reply.status(400).send({error:'status invalido'});\n  const c=await ctx.models.Client.findById(id);\n  if(!c)return ctx.reply.status(404).send({error:'Cliente nao encontrado'});\n  if(c.parentId)return ctx.reply.status(400).send({error:'Qualificacao so na matriz'});\n  if(!c.ownerId)return ctx.reply.status(403).send({error:'Pegue o lead antes de editar'});\n  const fil=await ctx.models.Client.findMany({parentId:id});\n  const qtd=1+fil.length;\n  function ct(q,s){let x=q>=10?3:q>=3?2:1;if(s==='qualificado')x+=2;else if(s==='em_contato')x+=1;else if(s==='sem_interesse'||s==='descartado')x-=2;if(x>=5)return'muito_quente';if(x>=4)return'quente';if(x>=2)return'morno';return'frio';}\n  const upd=await ctx.models.Client.update(id,{status:st,temperaturaCalculada:ct(qtd,st)});\n  if(c.status!==st){\n    await ctx.models.LeadStatusHistory.create({id:'c'+Date.now().toString(36)+Math.random().toString(36).slice(2,10),clientId:id,fromStatus:c.status||null,toStatus:st,changedById:uid,changedAt:new Date().toISOString()});\n  }\n  return ctx.reply.send(upd);\n}\nmodule.exports={handler};\n"),
  },
  // 49 crm-domain-leads POST /deals/:id/mover (95916365)
  {
    module: "crm-domain-leads",
    method: "POST",
    path: "/deals/:id/mover",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cmtamn51j00t8qd011mvi648n",
    handler: compileController("async function handler(ctx){\n  const uid=ctx.user&&ctx.user.id; if(!uid) return ctx.reply.status(401).send({error:'Auth necessaria'});\n  const id=ctx.params.id; const b=ctx.body||{}; const stageId=b.stageId;\n  if(!stageId) return ctx.reply.status(400).send({error:'stageId obrigatorio'});\n  const deal=await ctx.models.Deal.findById(id); if(!deal) return ctx.reply.status(404).send({error:'Negociacao nao encontrada'});\n  const stages=await ctx.models.Stage.findMany({});\n  const alvo=stages.find(s=>s.id===stageId); const nome=alvo?alvo.name:'';\n  if(nome==='Demo agendada' && !b.forcar){\n    const c=await ctx.models.Client.findById(deal.clientId); const faltam=[];\n    if(c){ if(!c.segmento) faltam.push('segmento'); if(c.qtdCaixas==null) faltam.push('qtdCaixas'); if(!c.dorDeclarada) faltam.push('dorDeclarada'); }\n    if(faltam.length) return ctx.reply.send({needQualificacao:true, clientId:deal.clientId, faltam});\n  }\n  const hist=Array.isArray(deal.stageHistory)?deal.stageHistory.slice():[];\n  hist.push({stageId,at:new Date().toISOString()});\n  const patch={stageId,stageHistory:hist};\n  if(nome==='Fechamento'){ patch.status='won'; patch.closedAt=new Date().toISOString(); }\n  const upd=await ctx.models.Deal.update(id,patch);\n  let d30=false;\n  if(nome==='Fechamento'){\n    await ctx.models.Activity.create({id:'c'+Date.now().toString(36)+Math.random().toString(36).slice(2,10),type:'follow_up',clientId:deal.clientId,dealId:id,ownerId:uid,scheduledAt:new Date(Date.now()+30*86400000).toISOString(),notes:'Pos-30: pedir indicacao (Modulo 05). \"Quem voce conhece que tem uma loja parecida e ia gostar de conhecer isso?\"',reminderSent:false,createdAt:new Date().toISOString()});\n    d30=true;\n  }\n  return ctx.reply.send({deal:upd, atividadeD30:d30});\n}\nmodule.exports={handler};\n"),
  },
  // 50 crm-domain-leads POST /deals/save (40a6f2f8)
  {
    module: "crm-domain-leads",
    method: "POST",
    path: "/deals/save",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cmtamn4p600t6qd01j6jmcq28",
    handler: compileController("async function handler(ctx){\n  const uid=ctx.user&&ctx.user.id; if(!uid) return ctx.reply.status(401).send({error:'Auth necessaria'});\n  const b=ctx.body||{};\n  if(!b.title||!b.clientId||!b.stageId) return ctx.reply.status(400).send({error:'Titulo, cliente e etapa sao obrigatorios'});\n  const qtd=Math.max(1,Number(b.qtdLojas)||1);\n  const mensal=Number(b.valorMensalLoja)||0;\n  const desc=Number(b.descontoPct)||0;\n  const value=Math.round(mensal*qtd*(1-desc/100)*100)/100;\n  const avisos=[];\n  if(b.plano==='start'){ const c=await ctx.models.Client.findById(b.clientId); if(c&&Number(c.qtdCaixas)>1) avisos.push('Start nao tem compras nem relatorio. O treinamento recomenda o Core — vender Start para quem precisa de Core cancela em 60 dias (Modulo 04).'); }\n  if(desc>10) avisos.push('Desconto acima de 10% — marcado como pendente de aprovacao do gerente (Modulo 09).');\n  const data={ title:b.title, clientId:b.clientId, stageId:b.stageId, ownerId:uid, status:b.status||'open',\n    plano:b.plano||null, qtdLojas:qtd, valorMensalLoja:mensal||null, descontoPct:desc||null, value, pendenteAprovacao:desc>10 };\n  let deal;\n  if(b.id){ deal=await ctx.models.Deal.update(b.id,data); }\n  else { data.id='c'+Date.now().toString(36)+Math.random().toString(36).slice(2,10); data.createdAt=new Date().toISOString(); data.stageHistory=[{stageId:b.stageId,at:new Date().toISOString()}]; deal=await ctx.models.Deal.create(data); }\n  return ctx.reply.send({deal,avisos});\n}\nmodule.exports={handler};\n"),
  },
  // 51 crm-domain-leads POST /equipe/membro (9dcb58b5)
  {
    module: "crm-domain-leads",
    method: "POST",
    path: "/equipe/membro",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cmtanx45a00toqd013t6tah04",
    handler: compileController("async function handler(ctx){\n  const uid=ctx.user&&ctx.user.id; if(!uid) return ctx.reply.status(401).send({error:'Auth necessaria'});\n  const me=await ctx.models.Profile.findById(uid);\n  if(!me||me.role!=='admin') return ctx.reply.status(403).send({error:'Apenas admin do CRM'});\n  const b=ctx.body||{};\n  if(!b.id||!b.role) return ctx.reply.status(400).send({error:'id e role obrigatorios'});\n  const roles=['vendedor','gerente','admin']; if(roles.indexOf(b.role)<0) return ctx.reply.status(400).send({error:'role invalido'});\n  const ex=await ctx.models.Profile.findById(b.id);\n  const data={email:b.email||null,fullName:b.name||b.fullName||null,role:b.role,phone:b.phone||null,active:b.active!==false};\n  const prof=ex ? await ctx.models.Profile.update(b.id,data) : await ctx.models.Profile.create({id:b.id,...data});\n  return ctx.reply.send(prof);\n}\nmodule.exports={handler};\n"),
  },
  // 52 crm-domain-leads POST /leads/claim-bulk (cc47b3c9)
  {
    module: "crm-domain-leads",
    method: "POST",
    path: "/leads/claim-bulk",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms5957fo001fmt010ggosero",
    handler: compileController("async function handler(ctx){\n  const ids=(ctx.body&&ctx.body.ids)||[];const uid=ctx.user&&ctx.user.id;\n  if(!uid)return ctx.reply.status(401).send({error:'Auth necessaria'});\n  if(!Array.isArray(ids)||!ids.length)return ctx.reply.status(400).send({error:'Selecione ao menos um lead'});\n  if(ids.length>50)return ctx.reply.status(400).send({error:'Maximo 50 por vez'});\n  let pegos=0;\n  for(const id of ids){\n    const c=await ctx.models.Client.findById(id);\n    if(c&&!c.ownerId&&!c.parentId){\n      await ctx.models.Client.update(id,{ownerId:uid});pegos++;\n      const fil=await ctx.models.Client.findMany({parentId:id});\n      for(const f of fil){await ctx.models.Client.update(f.id,{ownerId:uid});}\n    }\n  }\n  const perd=ids.length-pegos;\n  const message=perd>0?('Pegou '+pegos+' de '+ids.length+' — '+perd+' ja haviam sido pegos.'):('Pegou '+pegos+(pegos===1?' lead.':' leads.'));\n  return ctx.reply.send({pedidos:ids.length,pegos,message});\n}\nmodule.exports={handler};\n"),
  },
  // 53 crm-domain-leads POST /produtos (059333d2)
  {
    module: "crm-domain-leads",
    method: "POST",
    path: "/produtos",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms598uec0029mt01hromobch",
    handler: compileController("async function handler(ctx){\n  const nome=((ctx.body&&ctx.body.nome)||'').trim();\n  if(!nome)return ctx.reply.status(400).send({error:'nome obrigatorio'});\n  const all=await ctx.models.Produto.findMany({});\n  const ex=all.find(x=>((x.nome||'').toLowerCase())===nome.toLowerCase());\n  if(ex)return ctx.reply.send(ex);\n  const c=await ctx.models.Produto.create({id:'c'+Date.now().toString(36)+Math.random().toString(36).slice(2,10),nome,ativo:true,createdAt:new Date().toISOString()});\n  return ctx.reply.status(201).send(c);\n}\nmodule.exports={handler};\n"),
  },
  // 54 crm-domain-leads POST /ramos (7f2e0670)
  {
    module: "crm-domain-leads",
    method: "POST",
    path: "/ramos",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms595aa7001vmt01qy7o8dw4",
    handler: compileController("async function handler(ctx){\n  const nome=((ctx.body&&ctx.body.nome)||'').trim();\n  if(!nome)return ctx.reply.status(400).send({error:'nome obrigatorio'});\n  const all=await ctx.models.Ramo.findMany({});\n  const ex=all.find(x=>((x.nome||'').toLowerCase())===nome.toLowerCase());\n  if(ex)return ctx.reply.send(ex);\n  const c=await ctx.models.Ramo.create({id:'c'+Date.now().toString(36)+Math.random().toString(36).slice(2,10),nome,createdAt:new Date().toISOString()});\n  return ctx.reply.status(201).send(c);\n}\nmodule.exports={handler};\n"),
  },
  // 55 crm-domain-leads POST /senha/redefinir (96d8b9c4)
  {
    module: "crm-domain-leads",
    method: "POST",
    path: "/senha/redefinir",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cmtanzm5i00tuqd01ivaor48s",
    handler: compileController("async function handler(ctx){\n  return ctx.reply.status(503).send({error:'A recuperacao por WhatsApp ainda nao esta conectada.'});\n}\nmodule.exports={handler};\n"),
  },
  // 56 crm-domain-leads POST /senha/solicitar (ba4336da)
  {
    module: "crm-domain-leads",
    method: "POST",
    path: "/senha/solicitar",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cmtanzlt700tsqd01erg14zci",
    handler: compileController("// STUB (Fase futura): recuperacao por WhatsApp. Envia codigo ao WhatsApp do cadastro.\nasync function handler(ctx){\n  return ctx.reply.status(503).send({error:'A recuperacao por WhatsApp ainda nao esta conectada. Fale com um administrador para redefinir sua senha.'});\n}\nmodule.exports={handler};\n"),
  },
  // 57 crm-domain-leads POST /termo/accept (cb916b95)
  {
    module: "crm-domain-leads",
    method: "POST",
    path: "/termo/accept",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms595848001jmt018t863egx",
    handler: compileController("async function handler(ctx){\n  const uid=ctx.user&&ctx.user.id;if(!uid)return ctx.reply.status(401).send({error:'Auth necessaria'});\n  const terms=await ctx.models.Term.findMany({});\n  const cur=terms.filter(t=>t.vigente).sort((a,b)=>((b.publishedAt||'')+'').localeCompare((a.publishedAt||'')+''))[0];\n  if(!cur)return ctx.reply.status(400).send({error:'Nenhum termo vigente'});\n  const acc=await ctx.models.TermAcceptance.findMany({userId:uid});\n  if(!acc.some(a=>a.versao===cur.versao)){\n    await ctx.models.TermAcceptance.create({id:'c'+Date.now().toString(36)+Math.random().toString(36).slice(2,10),userId:uid,versao:cur.versao,acceptedAt:new Date().toISOString(),ip:null,userAgent:(ctx.body&&ctx.body.userAgent)||null});\n  }\n  return ctx.reply.send({success:true,versao:cur.versao});\n}\nmodule.exports={handler};\n"),
  },
  // 58 crm-domain-leads POST /termo/publish (7eedfd5f)
  {
    module: "crm-domain-leads",
    method: "POST",
    path: "/termo/publish",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms5958gh001lmt0130iqc0li",
    handler: compileController("async function handler(ctx){\n  const uid=ctx.user&&ctx.user.id;if(!uid)return ctx.reply.status(401).send({error:'Auth necessaria'});\n  const prof=await ctx.models.Profile.findById(uid);\n  if(!prof||prof.role!=='admin')return ctx.reply.status(403).send({error:'Apenas admin do app'});\n  const b=ctx.body||{};if(!b.versao||!b.conteudo)return ctx.reply.status(400).send({error:'versao e conteudo obrigatorios'});\n  const terms=await ctx.models.Term.findMany({});\n  for(const t of terms){if(t.vigente)await ctx.models.Term.update(t.id,{vigente:false});}\n  const created=await ctx.models.Term.create({id:'c'+Date.now().toString(36)+Math.random().toString(36).slice(2,10),versao:b.versao,conteudo:b.conteudo,vigente:true,publishedById:uid,publishedAt:new Date().toISOString()});\n  return ctx.reply.status(201).send(created);\n}\nmodule.exports={handler};\n"),
  },
  // 59 crm-domain-leads POST /termo/reset (db99bf89)
  {
    module: "crm-domain-leads",
    method: "POST",
    path: "/termo/reset",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms5blzpo00ehmt015e8eofs3",
    handler: compileController("async function handler(ctx){ return ctx.reply.status(403).send({error:'desabilitado'}); }\nmodule.exports={handler};\n"),
  },
  // 60 crm-domain-leads POST /treinamento/progresso (1d6e4e75)
  {
    module: "crm-domain-leads",
    method: "POST",
    path: "/treinamento/progresso",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cmtam8aq400t2qd01b8vvfig9",
    handler: compileController("async function handler(ctx){\n  const uid=ctx.user&&ctx.user.id; if(!uid) return ctx.reply.status(401).send({error:'Auth necessaria'});\n  const mid=ctx.body&&ctx.body.moduloId; if(!mid) return ctx.reply.status(400).send({error:'moduloId obrigatorio'});\n  const feito=ctx.body.feito!==false;\n  const rows=await ctx.models.ProgressoTreinamento.findMany({userId:uid});\n  const ex=rows.find(r=>r.moduloId===mid);\n  if(feito && !ex){ await ctx.models.ProgressoTreinamento.create({id:'c'+Date.now().toString(36)+Math.random().toString(36).slice(2,10),userId:uid,moduloId:mid,concluidoEm:new Date().toISOString()}); }\n  if(!feito && ex){ await ctx.models.ProgressoTreinamento.delete(ex.id); }\n  return ctx.reply.send({success:true,moduloId:mid,feito});\n}\nmodule.exports={handler};\n"),
  },
  // 61 deal DELETE /Deal/:id (9c1fa1f0)
  {
    module: "deal",
    method: "DELETE",
    path: "/Deal/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequ70023mk5skmx67hnh",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Deal;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Deal missing\" });\n  try {\n    await model.delete(String(ctx.params.id));\n    return ctx.reply.send({ ok: true });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 62 deal GET /Deal (d3d8c5d7)
  {
    module: "deal",
    method: "GET",
    path: "/Deal",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequ3001tmk5sy8vso0jv",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Deal;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Deal missing\" });\n  const rows = await model.findMany(ctx.query || {});\n  return ctx.reply.send({ data: rows, count: rows.length });\n}\nmodule.exports = { handler };"),
  },
  // 63 deal GET /Deal/:id (23aff3bb)
  {
    module: "deal",
    method: "GET",
    path: "/Deal/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequ4001xmk5syt8tco1g",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Deal;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Deal missing\" });\n  const row = await model.findById(String(ctx.params.id));\n  if (!row) return ctx.reply.status(404).send({ error: \"not found\" });\n  return ctx.reply.send({ data: row });\n}\nmodule.exports = { handler };"),
  },
  // 64 deal PATCH /Deal/:id (d58973de)
  {
    module: "deal",
    method: "PATCH",
    path: "/Deal/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequ5001zmk5s8605wfrw",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Deal;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Deal missing\" });\n  try {\n    const row = await model.update(String(ctx.params.id), Object.assign({}, ctx.body || {}));\n    return ctx.reply.send({ data: row });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 65 deal POST /Deal (0004599a)
  {
    module: "deal",
    method: "POST",
    path: "/Deal",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequ4001vmk5sn4kp9ynl",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Deal;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Deal missing\" });\n  const row = await model.create(Object.assign({}, ctx.body || {}));\n  return ctx.reply.status(201).send({ data: row });\n}\nmodule.exports = { handler };"),
  },
  // 66 deal PUT /Deal/:id (9c69c377)
  {
    module: "deal",
    method: "PUT",
    path: "/Deal/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequ60021mk5seumzzu9z",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Deal;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Deal missing\" });\n  try {\n    const row = await model.update(String(ctx.params.id), Object.assign({}, ctx.body || {}));\n    return ctx.reply.send({ data: row });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 67 goal DELETE /Goal/:id (f7d7dc0d)
  {
    module: "goal",
    method: "DELETE",
    path: "/Goal/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequc002hmk5sqfjmw4hu",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Goal;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Goal missing\" });\n  try {\n    await model.delete(String(ctx.params.id));\n    return ctx.reply.send({ ok: true });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 68 goal GET /Goal (90938631)
  {
    module: "goal",
    method: "GET",
    path: "/Goal",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequ80027mk5s3vk680hl",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Goal;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Goal missing\" });\n  const rows = await model.findMany(ctx.query || {});\n  return ctx.reply.send({ data: rows, count: rows.length });\n}\nmodule.exports = { handler };"),
  },
  // 69 goal GET /Goal/:id (35533d81)
  {
    module: "goal",
    method: "GET",
    path: "/Goal/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequa002bmk5sr898tiyu",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Goal;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Goal missing\" });\n  const row = await model.findById(String(ctx.params.id));\n  if (!row) return ctx.reply.status(404).send({ error: \"not found\" });\n  return ctx.reply.send({ data: row });\n}\nmodule.exports = { handler };"),
  },
  // 70 goal PATCH /Goal/:id (afc87da2)
  {
    module: "goal",
    method: "PATCH",
    path: "/Goal/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequb002dmk5swpbwg4b2",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Goal;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Goal missing\" });\n  try {\n    const row = await model.update(String(ctx.params.id), Object.assign({}, ctx.body || {}));\n    return ctx.reply.send({ data: row });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 71 goal POST /Goal (a45b5e8a)
  {
    module: "goal",
    method: "POST",
    path: "/Goal",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequ90029mk5sd5b1dx22",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Goal;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Goal missing\" });\n  const row = await model.create(Object.assign({}, ctx.body || {}));\n  return ctx.reply.status(201).send({ data: row });\n}\nmodule.exports = { handler };"),
  },
  // 72 goal PUT /Goal/:id (042d7e3c)
  {
    module: "goal",
    method: "PUT",
    path: "/Goal/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequc002fmk5snq81yohi",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Goal;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Goal missing\" });\n  try {\n    const row = await model.update(String(ctx.params.id), Object.assign({}, ctx.body || {}));\n    return ctx.reply.send({ data: row });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 73 probe GET /probe (4a318b34)
  {
    module: "probe",
    method: "GET",
    path: "/probe",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms58yi5g000zmt018ga3v4rx",
    handler: compileController("async function handler(ctx){ const m=ctx.models&&ctx.models.Client; const fns=m?Object.getOwnPropertyNames(Object.getPrototypeOf(m)).concat(Object.keys(m)).filter(k=>{try{return typeof m[k]==='function'}catch(e){return false}}):null; const ctxKeys=Object.keys(ctx); const has={updateMany:!!(m&&m.updateMany),count:!!(m&&m.count),deleteMany:!!(m&&m.deleteMany),tx:!!(ctx.tx||ctx.transaction||ctx.prisma),user:!!ctx.user}; return ctx.reply.send({fns,ctxKeys,has}); } module.exports={handler};"),
  },
  // 74 profile DELETE /Profile/:id (8c2dd7ce)
  {
    module: "profile",
    method: "DELETE",
    path: "/Profile/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequi002vmk5ss3ztumvj",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Profile;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Profile missing\" });\n  try {\n    await model.delete(String(ctx.params.id));\n    return ctx.reply.send({ ok: true });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 75 profile GET /Profile (85c4af35)
  {
    module: "profile",
    method: "GET",
    path: "/Profile",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3ueque002lmk5sef3zhndb",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Profile;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Profile missing\" });\n  const rows = await model.findMany(ctx.query || {});\n  return ctx.reply.send({ data: rows, count: rows.length });\n}\nmodule.exports = { handler };"),
  },
  // 76 profile GET /Profile/:id (fdfb8873)
  {
    module: "profile",
    method: "GET",
    path: "/Profile/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequg002pmk5sqs50d16c",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Profile;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Profile missing\" });\n  const row = await model.findById(String(ctx.params.id));\n  if (!row) return ctx.reply.status(404).send({ error: \"not found\" });\n  return ctx.reply.send({ data: row });\n}\nmodule.exports = { handler };"),
  },
  // 77 profile PATCH /Profile/:id (c27b1dfb)
  {
    module: "profile",
    method: "PATCH",
    path: "/Profile/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequg002rmk5s9qzloyao",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Profile;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Profile missing\" });\n  try {\n    const row = await model.update(String(ctx.params.id), Object.assign({}, ctx.body || {}));\n    return ctx.reply.send({ data: row });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 78 profile POST /Profile (18079a9a)
  {
    module: "profile",
    method: "POST",
    path: "/Profile",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequf002nmk5sdzsyklvo",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Profile;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Profile missing\" });\n  const row = await model.create(Object.assign({}, ctx.body || {}));\n  return ctx.reply.status(201).send({ data: row });\n}\nmodule.exports = { handler };"),
  },
  // 79 profile PUT /Profile/:id (9df2aa48)
  {
    module: "profile",
    method: "PUT",
    path: "/Profile/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequh002tmk5sm45sz8f4",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Profile;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Profile missing\" });\n  try {\n    const row = await model.update(String(ctx.params.id), Object.assign({}, ctx.body || {}));\n    return ctx.reply.send({ data: row });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 80 stage DELETE /Stage/:id (41847253)
  {
    module: "stage",
    method: "DELETE",
    path: "/Stage/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequo0039mk5slgarwamu",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Stage;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Stage missing\" });\n  try {\n    await model.delete(String(ctx.params.id));\n    return ctx.reply.send({ ok: true });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 81 stage GET /Stage (4c312545)
  {
    module: "stage",
    method: "GET",
    path: "/Stage",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequk002zmk5sja8vjvn1",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Stage;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Stage missing\" });\n  const rows = await model.findMany(ctx.query || {});\n  return ctx.reply.send({ data: rows, count: rows.length });\n}\nmodule.exports = { handler };"),
  },
  // 82 stage GET /Stage/:id (9294a0d2)
  {
    module: "stage",
    method: "GET",
    path: "/Stage/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequl0033mk5s79rx9lcy",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Stage;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Stage missing\" });\n  const row = await model.findById(String(ctx.params.id));\n  if (!row) return ctx.reply.status(404).send({ error: \"not found\" });\n  return ctx.reply.send({ data: row });\n}\nmodule.exports = { handler };"),
  },
  // 83 stage PATCH /Stage/:id (45543380)
  {
    module: "stage",
    method: "PATCH",
    path: "/Stage/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequm0035mk5sp2nvf9gi",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Stage;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Stage missing\" });\n  try {\n    const row = await model.update(String(ctx.params.id), Object.assign({}, ctx.body || {}));\n    return ctx.reply.send({ data: row });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 84 stage POST /Stage (b51ba88e)
  {
    module: "stage",
    method: "POST",
    path: "/Stage",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequl0031mk5s9hkriw72",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Stage;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Stage missing\" });\n  const row = await model.create(Object.assign({}, ctx.body || {}));\n  return ctx.reply.status(201).send({ data: row });\n}\nmodule.exports = { handler };"),
  },
  // 85 stage PUT /Stage/:id (1a34e2c9)
  {
    module: "stage",
    method: "PUT",
    path: "/Stage/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequn0037mk5sztxta375",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Stage;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Stage missing\" });\n  try {\n    const row = await model.update(String(ctx.params.id), Object.assign({}, ctx.body || {}));\n    return ctx.reply.send({ data: row });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 86 team DELETE /Team/:id (4ad875c5)
  {
    module: "team",
    method: "DELETE",
    path: "/Team/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequu003nmk5smjapgrzf",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Team;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Team missing\" });\n  try {\n    await model.delete(String(ctx.params.id));\n    return ctx.reply.send({ ok: true });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 87 team GET /Team (de93721b)
  {
    module: "team",
    method: "GET",
    path: "/Team",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequq003dmk5shg37x2nr",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Team;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Team missing\" });\n  const rows = await model.findMany(ctx.query || {});\n  return ctx.reply.send({ data: rows, count: rows.length });\n}\nmodule.exports = { handler };"),
  },
  // 88 team GET /Team/:id (12a07a8c)
  {
    module: "team",
    method: "GET",
    path: "/Team/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequr003hmk5soum331yi",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Team;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Team missing\" });\n  const row = await model.findById(String(ctx.params.id));\n  if (!row) return ctx.reply.status(404).send({ error: \"not found\" });\n  return ctx.reply.send({ data: row });\n}\nmodule.exports = { handler };"),
  },
  // 89 team PATCH /Team/:id (38e3b6f2)
  {
    module: "team",
    method: "PATCH",
    path: "/Team/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequs003jmk5sbi7m0x5u",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Team;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Team missing\" });\n  try {\n    const row = await model.update(String(ctx.params.id), Object.assign({}, ctx.body || {}));\n    return ctx.reply.send({ data: row });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 90 team POST /Team (26ad64c7)
  {
    module: "team",
    method: "POST",
    path: "/Team",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequq003fmk5s8wvcgzrc",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Team;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Team missing\" });\n  const row = await model.create(Object.assign({}, ctx.body || {}));\n  return ctx.reply.status(201).send({ data: row });\n}\nmodule.exports = { handler };"),
  },
  // 91 team PUT /Team/:id (1d8ab4c1)
  {
    module: "team",
    method: "PUT",
    path: "/Team/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequt003lmk5sfnaf98jz",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.Team;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model Team missing\" });\n  try {\n    const row = await model.update(String(ctx.params.id), Object.assign({}, ctx.body || {}));\n    return ctx.reply.send({ data: row });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 92 user DELETE /User/:id (8aec6cd3)
  {
    module: "user",
    method: "DELETE",
    path: "/User/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequz0041mk5sze4dan0z",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.User;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model User missing\" });\n  try {\n    await model.delete(String(ctx.params.id));\n    return ctx.reply.send({ ok: true });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 93 user GET /User (46f1bba8)
  {
    module: "user",
    method: "GET",
    path: "/User",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequv003rmk5s0f7px8zs",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.User;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model User missing\" });\n  const rows = await model.findMany(ctx.query || {});\n  return ctx.reply.send({ data: rows, count: rows.length });\n}\nmodule.exports = { handler };"),
  },
  // 94 user GET /User/:id (d9717ce9)
  {
    module: "user",
    method: "GET",
    path: "/User/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequx003vmk5serbvnfjx",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.User;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model User missing\" });\n  const row = await model.findById(String(ctx.params.id));\n  if (!row) return ctx.reply.status(404).send({ error: \"not found\" });\n  return ctx.reply.send({ data: row });\n}\nmodule.exports = { handler };"),
  },
  // 95 user PATCH /User/:id (113886df)
  {
    module: "user",
    method: "PATCH",
    path: "/User/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequy003xmk5sgxz5ejar",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.User;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model User missing\" });\n  try {\n    const row = await model.update(String(ctx.params.id), Object.assign({}, ctx.body || {}));\n    return ctx.reply.send({ data: row });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  },
  // 96 user POST /User (a7ac08e0)
  {
    module: "user",
    method: "POST",
    path: "/User",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequw003tmk5sg5kiee42",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.User;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model User missing\" });\n  const row = await model.create(Object.assign({}, ctx.body || {}));\n  return ctx.reply.status(201).send({ data: row });\n}\nmodule.exports = { handler };"),
  },
  // 97 user PUT /User/:id (a0d42b25)
  {
    module: "user",
    method: "PUT",
    path: "/User/:id",
    authMode: "actor",
    webhookSecretName: null,
    requiredPermissions: [],
    source: "cms3uequz003zmk5semfbp43d",
    handler: compileController("async function handler(ctx) {\n  const model = ctx.models.User;\n  if (!model) return ctx.reply.status(500).send({ error: \"Model User missing\" });\n  try {\n    const row = await model.update(String(ctx.params.id), Object.assign({}, ctx.body || {}));\n    return ctx.reply.send({ data: row });\n  } catch (e) {\n    return ctx.reply.status(404).send({ error: String(e.message || e) });\n  }\n}\nmodule.exports = { handler };"),
  }
]
